package gov.nih.nci.cagrid.identifiers.common;

import java.rmi.RemoteException;

/**
 * The Naming Authority service enables users to maintain and resolve identifiers in the grid
 *
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.3
 * 
 */
public interface IdentifiersNAServiceI {

  public org.oasis.wsrf.properties.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis.wsrf.properties.GetMultipleResourceProperties_Element params) throws RemoteException ;

  public org.oasis.wsrf.properties.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName params) throws RemoteException ;

  public org.oasis.wsrf.properties.QueryResourcePropertiesResponse queryResourceProperties(org.oasis.wsrf.properties.QueryResourceProperties_Element params) throws RemoteException ;

  /**
   * Creates a new identifier using the provided metadata (IdentifierValues)
   *
   * @param identifierData
   *	Identifier metadata to be associated with the new identifier
   * @return The new identifier generated by the naming authority
   * @throws NamingAuthorityConfigurationFault
   *	A configuration error was detected by the naming authority
   * @throws InvalidIdentifierFault
   *	The provided identifier is invalid, or does not exist
   * @throws NamingAuthoritySecurityFault
   *	User is not authorized to perform the operation
   * @throws InvalidIdentifierValuesFault
   *	Invalid identifier values (metadata) were provided by the user
   */
  public org.apache.axis.types.URI createIdentifier(namingauthority.IdentifierData identifierData) throws RemoteException, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthorityConfigurationFault, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthoritySecurityFault, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierValuesFault ;

  /**
   * Returns metadata associated with the provided identifier
   *
   * @param identifier
   *	The identifier to retrieve data from
   * @return The metadata associated with the provided identifier
   * @throws NamingAuthorityConfigurationFault
   *	A configuration error has been detected
   * @throws InvalidIdentifierFault
   *	The provided identifier does not exist
   * @throws NamingAuthoritySecurityFault
   *	User is not authorized to perform the operation
   */
  public namingauthority.IdentifierData resolveIdentifier(org.apache.axis.types.URI identifier) throws RemoteException, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthorityConfigurationFault, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthoritySecurityFault ;

  /**
   * Deletes keys from an identifier
   *
   * @param identifier
   *	The identifier to be modified
   * @param keyNames
   *	Names of keys to be deleted
   * @throws InvalidIdentifierFault
   *	The provided identifier does not exist
   * @throws NamingAuthorityConfigurationFault
   *	A configuration error has been detected
   * @throws NamingAuthoritySecurityFault
   *	User is not authorized to perform the operation
   * @throws InvalidIdentifierValuesFault
   *	Invalid identifier metadata was provided
   */
  public void deleteKeys(org.apache.axis.types.URI identifier,java.lang.String[] keyNames) throws RemoteException, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthorityConfigurationFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthoritySecurityFault, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierValuesFault ;

  /**
   * Creates new keys on an existing identifier
   *
   * @param identifier
   *	The identifier to be modified
   * @param identifierData
   *	The metadata to be added to the identifier 
   * @throws InvalidIdentifierFault
   *	The input identifier does not exist
   * @throws NamingAuthorityConfigurationFault
   *	A configuration error has been detected
   * @throws NamingAuthoritySecurityFault
   *	User is not authorized to perform the operation
   * @throws InvalidIdentifierValuesFault
   *	Invalid identifier metadata was provided
   */
  public void createKeys(org.apache.axis.types.URI identifier,namingauthority.IdentifierData identifierData) throws RemoteException, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthorityConfigurationFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthoritySecurityFault, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierValuesFault ;

  /**
   * Replaces the values associated with the specified keys on an existing identifier
   *
   * @param identifier
   *	The identifier to make changes to
   * @param identifierValues
   *	New values to be associated with the existing keys
   * @throws InvalidIdentifierFault
   *	The provided identifier does not exist
   * @throws NamingAuthorityConfigurationFault
   *	A configuration error has been detected
   * @throws NamingAuthoritySecurityFault
   *	User is not authorized to perform the operation
   * @throws InvalidIdentifierValuesFault
   *	The provided identifier metadata does not exist
   */
  public void replaceKeyValues(org.apache.axis.types.URI identifier,namingauthority.IdentifierValues identifierValues) throws RemoteException, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthorityConfigurationFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthoritySecurityFault, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierValuesFault ;

  /**
   * Gets key names associated with an existing identifier
   *
   * @param identifier
   *	The identifier to retrieve data from
   * @return The list of key names associated with the identifier
   * @throws InvalidIdentifierFault
   *	The provided identifier does not exist
   * @throws NamingAuthorityConfigurationFault
   *	A configuration error has been detected
   * @throws NamingAuthoritySecurityFault
   *	User is not authorized to perform the operation
   */
  public java.lang.String[] getKeyNames(org.apache.axis.types.URI identifier) throws RemoteException, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthorityConfigurationFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthoritySecurityFault ;

  /**
   * Gets data associated with the given key
   *
   * @param identifier
   *	The identifier to retrieve data from
   * @param keyName
   *	They key name to retrieve data from
   * @return The values associated with the provided key name
   * @throws InvalidIdentifierFault
   *	The provided identifier does not exist
   * @throws NamingAuthoritySecurityFault
   *	User is not authorized to perform the operation
   * @throws NamingAuthorityConfigurationFault
   *	A configuration error has been detected
   * @throws InvalidIdentifierValuesFault
   *	
   */
  public namingauthority.KeyNameData getKeyData(org.apache.axis.types.URI identifier,java.lang.String keyName) throws RemoteException, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthoritySecurityFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthorityConfigurationFault, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierValuesFault ;

  /**
   * This operation registers a Specimen Identifier.
   *
   * @param suggestedIdentifer
   * @param parentIdentifiers
   * @throws NamingAuthorityConfigurationFault
   *	
   * @throws InvalidIdentifierValuesFault
   *	
   * @throws InvalidIdentifierFault
   *	
   * @throws NamingAuthoritySecurityFault
   *	
   */
  public java.lang.String registerGSID(java.lang.String suggestedIdentifer,java.lang.String[] parentIdentifiers) throws RemoteException, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthorityConfigurationFault, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierValuesFault, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthoritySecurityFault ;

  /**
   * Add the current user as an site that has information about the input specimen identifier.
   *
   * @param identifier
   * @throws NamingAuthorityConfigurationFault
   *	
   * @throws InvalidIdentifierValuesFault
   *	
   * @throws InvalidIdentifierFault
   *	
   * @throws NamingAuthoritySecurityFault
   *	
   */
  public org.apache.axis.types.URI addSite(java.lang.String identifier) throws RemoteException, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthorityConfigurationFault, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierValuesFault, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthoritySecurityFault ;

  /**
   * Generates a batch of valid UUIDs.
   *
   * @param numOfIdentifiers
   * @throws NamingAuthorityConfigurationFault
   *	
   * @throws NamingAuthoritySecurityFault
   *	
   */
  public java.lang.String[] generateIdentifiers(int numOfIdentifiers) throws RemoteException, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthorityConfigurationFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthoritySecurityFault ;

  /**
   * Return the parent hierarchy of the input Specimen Identifier
   *
   * @param identifier
   * @throws NamingAuthorityConfigurationFault
   *	
   * @throws NamingAuthoritySecurityFault
   *	
   * @throws InvalidIdentifierValuesFault
   *	
   * @throws InvalidIdentifierFault
   *	
   */
  public namingauthority.Tree getParentHierarchy(java.lang.String identifier) throws RemoteException, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthorityConfigurationFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthoritySecurityFault, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierValuesFault, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierFault ;

  /**
   * Return the parent hierarchy of the input Specimen Identifier.
   *
   * @param identifier
   * @throws NamingAuthorityConfigurationFault
   *	
   * @throws InvalidIdentifierFault
   *	
   * @throws InvalidIdentifierValuesFault
   *	
   * @throws NamingAuthoritySecurityFault
   *	
   */
  public namingauthority.Tree getChildHierarchy(java.lang.String identifier) throws RemoteException, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthorityConfigurationFault, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierFault, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierValuesFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthoritySecurityFault ;

  /**
   * Registers a Site.
   *
   * @param application
   * @param applicationURL
   * @param applicationVersion
   * @param contactName
   * @param contactEmail
   * @param contactPhone
   * @param organization
   * @throws InvalidIdentifierFault
   *	
   * @throws InvalidIdentifierValuesFault
   *	
   * @throws NamingAuthorityConfigurationFault
   *	
   * @throws NamingAuthoritySecurityFault
   *	
   */
  public void registerSite(java.lang.String application,java.lang.String applicationURL,java.lang.String applicationVersion,java.lang.String contactName,java.lang.String contactEmail,java.lang.String contactPhone,java.lang.String organization) throws RemoteException, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierFault, gov.nih.nci.cagrid.identifiers.stubs.types.InvalidIdentifierValuesFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthorityConfigurationFault, gov.nih.nci.cagrid.identifiers.stubs.types.NamingAuthoritySecurityFault ;

}

